### ISSUE TITLE
array_key_exists(): The first argument should be either a string or an integer

### ISSUE THREAD

**Issue by ariqd** [steevenz/rajaongkir#10]
saya coba install package via composer di laravel, setelah instalasi selesai muncul error berikut di semua route sehingga web tidak bisa digunakan. ketika package di-remove errornya hilang.

![rajaongkir error](https://user-images.githubusercontent.com/10435262/42252640-d42020ce-7f67-11e8-82a9-d17d94fc498f.png)

mohon bantuannya, terima kasih

**Comment by saputra1337** [comment]
Same Issue. 1+

**Comment by steevenz** [comment]
Untuk mengatasi coilision function name di Laravel Framework.. silahkan ganti nama function pada file vendor/o2system/kernel/src/Helpers/Kernel.php line 185 dan line 195 dari env ke environment
