### ISSUE TITLE
Error Dependency

### ISSUE THREAD

**Issue by faytranevozter** [steevenz/rajaongkir#17]
Saya baru saja menginstall fresh, dan ini yang muncul
<img width="1308" alt="Screen Shot 2019-10-25 at 04 14 10" src="https://user-images.githubusercontent.com/16716664/67525971-09da8800-f6de-11e9-9f58-a379b86ba9c2.png">
sepertinya error pada dependencynya.

Mungkin saya salah membuat issue disini, tapi saya ingin menggunakan fitur pada repo ini. Trimakasih

**Comment by steevenz** [comment]
Terima kasih untuk report issuesnya.. saya usahakan hari ini sudah dipush.. nanti cukup run composer update saja..

**Comment by steevenz** [comment]
halo.. silahkan run composer update.. seharusnya sudah solved..
