### ISSUE TITLE
E_URI_HAS_DISALLOWED_CHARACTERS

### ISSUE THREAD

**Issue by faytranevozter** [steevenz/rajaongkir#19]
Error ketika mendapatkan data waybill
```php
$rajaongkir->getWaybill('123456789', 'jne');
```
Kode diatas seharusnya tidak masalah. Tapi bermasalah jika url kita ada url yg tidak diperlukan dalam repo ini. Dalam kasus saya ada tanda `=` dalam url website saya yang menyebabkan error. Dan menurut saya errornya tidak nyambung. Karena seharusnya tidak masalah jika url saya ada karakter yang tidak diperbolehkan ketika memanggil fungsi waybill.

[EDIT]
Ternyata tidak cuma getWaybill, semua fungsi tidak bisa.

**Comment by steevenz** [comment]
![image](https://user-images.githubusercontent.com/218405/72949187-214b0f00-3dba-11ea-97d1-a850624ea04e.png)

Dikarenakan ini kasus khusus diluar O2System Framework.. silahkan tambahkan tanda = langsung ke dalam source code
/vendor/o2system/kernel/src/Http/Message/Uri/Segments.php (line 410)
seperti pada gambar.. atau download patch.zip yang saya sertakan disini.. extract dan replace source code diatas dengan file ini..

Terima kasih.. happy coding
[patch.zip](https://github.com/steevenz/rajaongkir/files/4100878/patch.zip)
