### ISSUE TITLE
URL Segment Problem

### ISSUE THREAD

**Issue by edyulianto** [steevenz/rajaongkir#20]
![image](https://user-images.githubusercontent.com/10769164/73255461-c3238f00-41f2-11ea-8858-3db6d3bf354c.png)

URI dari REST API yang saya buat, masuk kedalam URI pemanggilan rajaongkir

**Comment by steevenz** [comment]
apakah ini masih menjadi issued @edyulianto ? boleh japri saya di line.. nanti kita chat lebih lanjut..
