### ISSUE TITLE
can't get subdistrict with get_subdistricst($param) 

### ISSUE THREAD

**Issue by bakermeoe** [steevenz/rajaongkir#3]
Thank u for sharing this beautiful and useful code for us. I want to ask about getting the subdistrict from raja ongkir. I'm sure using the right method, but the result is Call to undefined method Steevenz\Rajaongkir::get_subdistricts. May you help me? thank u

**Comment by bakermeoe** [comment]
Oukayy.. I'm sorry I didn't read the issue before. there is typo with subdistrict method wkwkwkwkwkk. thank u very much :), have a great day

**Comment by bakermeoe** [comment]
get_subdisctricts(3), this is the right one. Thank u

**Comment by steevenz** [comment]
hi.. again.. i'll check ur bugs asap.. sorry for this inconvenience.. i've major update on Curl and Glob class.. an inform u immediately.. thanks for ur patience

Sent from Yahoo Mail on Android 

  On Thu, Aug 18, 2016 at 18:07, RichardOeynotifications@github.com wrote:  
Thank u for sharing this beautiful and useful code for us. I want to ask about getting the subdistrict from raja ongkir. I'm sure using the right method, but the result is Call to undefined method Steevenz\Rajaongkir::get_subdistricts. May you help me? thank u
