### ISSUE TITLE
Error Ketika Composer Require

### ISSUE THREAD

**Issue by icangku** [steevenz/rajaongkir#6]
> Illuminate\Foundation\ComposerScripts::postUpdate
PHP Fatal error:  Cannot use "static" when no class scope is active in /opt/lampp/htdocs/mxvistore-web/vendor/o2sys
tem/o2glob/src/Helpers/Inflector.php on line 121

Package o2system/o2gears is abandoned, you should avoid using it. Use o2system/gear instead.
Package o2system/o2glob is abandoned, you should avoid using it. Use o2system/kernel instead.
Package o2system/o2curl is abandoned, you should avoid using it. Use o2system/curl instead.

Tapi ketika melakukan composer require o2system/curl 

[InvalidArgumentException]
  Could not find package o2system/curl at any version for your minimum-stability (stable). Check the package spe
  lling or your minimum-stability

Thanks

**Comment by ucay** [comment]
Kalau mau pakai `o2system/curl`, pake `composer require o2system/curl:dev-master `.
Soalnya belum ada versi stable nya.
Atau set minimum-stability di `composer.json` ke dev.

**Comment by icangku** [comment]
Dicoba ya @ucay

**Comment by steevenz** [comment]
@masterpieceicang maaf ya.. versi rajaongkir yang baru belum saya upgrade dengan library curl yang baru.. tim kita sekarang ini lagi fokus untuk launching PHP Framework O2System v5.0.. kalo ada perlu bisa japri di line id: steevenz thank u

**Comment by steevenz** [comment]
Maaf lama baru bisa update.. Sekarang sudah berjalan kembali..
