### ISSUE TITLE
Composer Update error

### ISSUE THREAD

**Issue by JFOC** [steevenz/rajaongkir#9]
```
In MySqlConnector.php line 119:

  Object of class O2System\Kernel\Containers\Environment could not be converted to string

```
Sebelumnya tidak apa2 di Laravel 5.4
Bisakah fungsi curlnya memakai laravel saja ?

**Comment by ucay** [comment]
Bisa kasih info lebih jelas?
versi laravel, lalu config penggunaan rajaongkir ini bagaimana?

Sepertinya itu error dari laravelnya sih, bukan dari package ini.

**Comment by JFOC** [comment]
php artisan --version
Laravel Framework 5.4.36

Sebelumnya bekerja dengan baik. 
O2System ini salah satu package yang digunakan oleh RajaOngkir, dan itu yang menyebabkan error.

Masalah di atas saat composer update

**Comment by JFOC** [comment]
`    "o2system/curl": "*"
`

**Comment by ucay** [comment]
Baru tes di Laravel 5.4 - 5.6 fresh install, lalu require package muncul error ketika serve.

```bash
$ composer create-project --prefer-dist laravel/laravel test-rajaongkir "5.6.*"
$ cd test-rajaongkir
$ composer require steevenz/rajaongkir
$ php artisan serve
```
![screenshot from 2018-04-16 16-40-05](https://user-images.githubusercontent.com/3348846/38801953-645c28f6-4195-11e8-9aef-b1c98c3064e9.png)


NB : Jalan dengan lancar di framework Symfony 3.4

**Comment by steevenz** [comment]
Halo semua.. mohon maaf atas bugs yang disebabkan dari O2System\Kernel.. mohon tunggu update release di http://github/o2system/kernel 
Kemungkinan besar sekitar dini hari besok..

Untuk TCA bisa command dahulu beberapa line di file
[path-to-vendor]/o2system/kernel/src/Kernel.php
line 65-71
![image](https://user-images.githubusercontent.com/218405/38891257-f7e5d1c6-42ad-11e8-9fe2-c1d9a0b92ae9.png)

Terima Kasih.. Happy Coding..

**Comment by steevenz** [comment]
Dear all.. sudah ada update untuk O2System\Kernel packagenya.. issue ini saya close ya.. terima kasih semua.. happy coding
